### PR TITLE
Added list from rsdb and bannedwordlist

### PR DESCRIPTION
**Pull request by prabhu**

### CODE REVIEW

**Comment by wooorm** [comment]
Hi @prabhu, thanks for the helping!

I like the first commit you made, looks good 👍

The second commit contains lots of dirty data though: e.g., `Yo Boy/Girl`, first of all that should be split in `Yo Boy` and `Yo Girl` probably; secondly, the casing is weird; and thirdly, why is it even in there?

Some other cases: `Champi�on`, something went wrong with encoding here, `My Friend!`, why is that in there? There’s a duplicate `Oreo`, &c.

**Comment by wooorm** [comment]
@prabhu Ping!

**Comment by prabhu** [comment]
Ignore this list. I will clean it up and send you a new one.

**Comment by wooorm** [comment]
@prabhu 👍 

bannedwordlist.com is down; do you have a proper source, license for the first list?

**Comment by wooorm** [comment]
Closing due to no response.

**Pull request closed without merging**
